version: 1
disable_existing_loggers: false

formatters:
  default:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  file:
    class: logging.FileHandler
    level: INFO
    formatter: default
    filename: .runner.log
    mode: a

root:
  level: INFO
  handlers: [file]